### ISSUE TITLE
cannot connect lightpad to sc under mac sierra

### ISSUE THREAD

**Issue by caseyanderson** [scazan/BlocksOSC#2]
1. plug in lightpad to computer
2. lightpad powers up and does its normal "heartbeat" animation
3. run blocksosc
4. lightpad continues "heartbeat," no communication with sc possible

this is under mac os 10.12.3

**Comment by scazan** [comment]
I confirmed that this does, indeed, work under macOS Sierra. However, I have noticed that occasionally the Lightpad blocks will not be recognized and you have to unplug the USB cable and plug it back in again to get it to notice it.

I'm going to close this issue and start a new one here for that problem: https://github.com/scazan/blocksosc/issues/3
